#!/bin/bash
yum install httpd -y
echo '<h1> hello world from $(hostname -f) </h1>' > /var/www/index.html
echo '<h1> CheCheTech is where we Learn, Love, Linux </h1>' > /var/www/html/index.html
systemctl enable httpd
systemctl start httpd
